version: 1
accounts:
  - name: alice
    coins: ["20000token", "200000000ugrid"]
  - name: bob
    coins: ["10000token", "ugrid"]
validators:
  - name: alice
    bonded: "100000000ugrid"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
faucet:
  name: bob
  coins: ["5token", "100000ugrid"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "ugrid"
